### ISSUE TITLE
Program crashes when I hit an enemy

### ISSUE THREAD

**Issue by hipoojan** [thepasterover/alien_invasion#1]
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Fatal Python error: PyEval_SaveThread: NULL tstate

Current thread 0x00007fa233a09740 (most recent call first):
  File "/home/hipoojan/Projects/Python/alien_invasion/game_functions.py", line 244 in update_aliens
  File "/home/hipoojan/Projects/Python/alien_invasion/alien_invasion.py", line 60 in run_game
  File "/home/hipoojan/Projects/Python/alien_invasion/alien_invasion.py", line 66 in <module>
Aborted (core dumped)

**Comment by thepasterover** [comment]
Works fine on my system. 
![image](https://user-images.githubusercontent.com/50194033/57982480-b0519b80-7a63-11e9-9045-86418a25dea1.png)

Maybe you don't have audio libraries installed for pygame, run this code on terminal to install them. Try and let me know. I'll fix the code. Here:

>$ sudo apt-get install python3-dev mercurial
>$ sudo apt-get install libsdl-image1.2-dev libsdl2-dev libsdl-ttf2.0-dev

This will install the libraries needed to run Alien Invasion successfully.
If you want to enable some more advanced functionality in Pygame, such as
the ability to add sounds, you can also add the following libraries:

>$ sudo apt-get install libsdl-mixer1.2-dev libportmidi-dev
>$ sudo apt-get install libswscale-dev libsmpeg-dev libavformat-dev libavcode-dev
>$ sudo apt-get install python-numpy

Thanks

**Comment by stuartlangridge** [comment]
The underlying cause of this is probably an SDL bug, but in my experience it is possible to work around it by explicitly setting the frequency of the mixer in code. By default, in pygame 1, the mixer frequency is set to 22050; in pygame 2 it is set to 44100. Setting it to 44100 in pygame 1 stopped this crash happening for me:

```python
    pygame.mixer.pre_init(frequency=44100)
    pygame.init()
    pygame.mixer.init(frequency=44100)
```

It's not clear if both of these init settings for the mixer are needed, but it doesn't hurt to add both, and for me it stopped the crash.
